# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  path: 'backend'

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd $(path)
    npm install
    cd ..
  displayName: 'npm install and build'

- script: |
    cd $(path)
    npm run lint
    cd ..
  displayName: 'linting'

- script: |
    cd $(path)
    npm run test
    cd ..
  displayName: 'testing'
