trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - backend/*

variables:
  path: 'backend'

pool:
  vmImage: windows-latest

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: test
    displayName: 'Test the application'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(path)
        npm install
        cd ..
      displayName: 'npm install and build'

    - script: |
        cd $(path)
        npm run lint
        cd ..
      displayName: 'linting'

    - script: |
        cd $(path)
        npm run test
        cd ..
      displayName: 'testing'

  - job: build
    displayName: 'Build the application'
    dependsOn: 'test'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(path)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'backend'
        publishLocation: 'Container'

- stage: deploy_to_test
  displayName: 'Deploy to test'
  jobs:
  - job: 'deploy_to_test'
    steps:
    - download: 'CURRENT'
    displayName: 'Download Artifact: backend'
    artifact: backend